name = "hometab"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "709a287f1fa145e787e279cbf2c9133b"

[vars]
ENVIRONMENT = "development"

[[routes]]
pattern = "home.spotjoy.com"
custom_domain = true
